-- Seed model_catalog with all entries from prisma/seed.ts MODEL_CATALOG_ENTRIES.
-- Idempotent: ON CONFLICT ("model_id") DO NOTHING ensures safe re-runs and
-- safe prisma migrate deploy on fresh environments (prod, CI, new devs).
-- This is the canonical path for catalog data reaching any environment —
-- prisma db seed is local-dev only and does not run on deploy.

INSERT INTO "model_catalog" (
  "id",
  "model_id",
  "display_name",
  "provider",
  "description",
  "context_window",
  "input_cost_per_million",
  "output_cost_per_million",
  "is_free",
  "throughput_tokens_per_sec",
  "latency_seconds",
  "tool_call_error_rate",
  "structured_output_error_rate",
  "quality_index",
  "agentic_score",
  "tool_use_score",
  "instruction_following_score",
  "non_hallucination_rate",
  "supports_tools",
  "supports_structured_output",
  "is_active",
  "notes",
  "strengths",
  "weaknesses",
  "updated_at"
) VALUES
  (
    gen_random_uuid(),
    'minimax/minimax-m2.7',
    'MiniMax M2.7',
    'minimax',
    'Next-generation LLM designed for autonomous, real-world productivity. Strong agentic capabilities via multi-agent collaboration. Handles live debugging, financial modeling, and document generation. 56.2% on SWE-Pro, 57.0% on Terminal Bench 2.',
    205000,
    0.279,
    1.2,
    false,
    49.0,
    2.11,
    NULL,
    NULL,
    50.0,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'Current default model for all AI employees. Approved for production use.',
    'Balanced cost/performance. Currently the default model for new archetypes. Proven reliable in production for non-tool-calling workflows.',
    'Fails bash tool calling via OpenCodeGo (E2E verified 2026-06-03). Not frontier-tier. Use deepseek/deepseek-v4-flash instead when tool calling is required.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'zhipu/glm-5.1',
    'GLM-5.1',
    'zhipu',
    'Zhipu AI GLM-5.1 — best-in-class software engineering model with top SWE-Bench Pro scores (58.4%). Long-horizon agentic capability supporting up to 8-hour autonomous runs. MIT license. Compatible with Claude Code tooling.',
    202752,
    0.98,
    3.08,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. Best SWE-Bench Pro score among Go-catalog models.',
    'Best-in-class software engineering (SWE-Bench Pro 58.4%). Long-horizon agentic capability with runs up to 8 hours. Top CyberGym score (68.7%). Open-source MIT license. Compatible with Claude Code tooling.',
    'Text-only — no multimodal (vision/audio) support. Expensive token usage on long autonomous tasks. Relatively new with limited third-party benchmarking.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'zhipu/glm-5',
    'GLM-5',
    'zhipu',
    'Zhipu AI GLM-5 — strong open-source coding and agent model (744B total, 40B active). Leading BrowseComp score (62.0%). MIT license. Good balance of capability and cost.',
    202752,
    0.6,
    1.92,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. Predecessor to GLM-5.1; lower cost at reduced performance.',
    'Strong open-source model for coding and agent tasks (744B total, 40B active). Leading BrowseComp score (62.0%). MIT license. Good balance of capability and openness.',
    'Superseded by GLM-5.1 in most benchmarks. Text-only — no multimodal support. Not frontier-tier on latest coding benchmarks.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'moonshot/kimi-k2.5',
    'Kimi K2.5',
    'moonshot',
    'Moonshot Kimi K2.5 — native multimodal model with Agent Swarm architecture that orchestrates up to 100 sub-agents. Strong agentic search and long-horizon reasoning. 256K context window.',
    262144,
    0.4,
    1.9,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. Agent Swarm reduces latency 4.5x vs single-agent. Budget-friendly multimodal option.',
    'Native multimodal (vision + text). Agent Swarm architecture orchestrates up to 100 sub-agents, reducing latency 4.5x. Strong agentic search capabilities. 256K context window.',
    '256K context is smaller than competitors offering 1M. Older generation — superseded by Kimi K2.6. Agent Swarm less mature than K2.6''s 300-agent version.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'moonshot/kimi-k2.6',
    'Kimi K2.6',
    'moonshot',
    'Moonshot Kimi K2.6 — strongest open-weight reasoning model at release (AA Intelligence Index 54). Upgraded Agent Swarm with 300 sub-agents and proactive orchestration. Excellent long-horizon coding.',
    262144,
    0.684,
    3.42,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. Strongest open-weight model in Go catalog at release.',
    'Strongest open-weight reasoning model at release (AA Intelligence Index 54). Upgraded Agent Swarm with 300 sub-agents and proactive orchestration. Excellent long-horizon coding. 256K context.',
    '256K context window — half the size of 1M-context competitors. Vision support but no audio input. Open-weight but very large model footprint.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'xiaomi/mimo-v2.5-pro',
    'MiMo-V2.5-Pro',
    'xiaomi',
    'Xiaomi MiMo-V2.5-Pro — most token-efficient agentic model (ClawEval 64% at ~70K tokens). Perfect compiler build rate. Highest GDPVal-AA score (1581). 1M context window. MIT open-source.',
    1048576,
    0.435,
    0.87,
    false,
    47.0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. E2E verified reliable for bash tool calling (2026-06-03).',
    'Most token-efficient agentic model (ClawEval 64% at ~70K tokens). Perfect compiler build rate. Highest GDPVal-AA score (1581). 1M context window. MIT open-source. AA Intelligence Index 54.',
    'Text-only — no multimodal support. Slow inference (47 t/s). Very verbose outputs (92M tokens on AA eval). Large model footprint (1.02T total, 42B active).',
    NOW()
  ),
  (
    gen_random_uuid(),
    'xiaomi/mimo-v2.5',
    'MiMo-V2.5',
    'xiaomi',
    'Xiaomi MiMo-V2.5 — native multimodal (vision + audio input) agentic model with 1M context. Half the cost of MiMo-V2.5-Pro. Strong agentic capability for the size. MIT open-source.',
    1048576,
    0.14,
    0.28,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. E2E verified: may fail bash tool calling in some contexts.',
    'Native multimodal (vision + audio input). 1M context window. Half the cost of MiMo-V2.5-Pro. Strong agentic capability for the size. MIT open-source.',
    'Smaller model (310B/15B active) — less capable than Pro on hardest reasoning tasks. Less proven in production than Pro variant. E2E verified: may fail bash tool calling in some contexts.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'alibaba/qwen3.7-max',
    'Qwen3.7 Max',
    'alibaba',
    'Alibaba Qwen3.7 Max — flagship with 35-hour autonomous coding runs. AA Intelligence Index 56.6 (#5 global). APEX 44.5 (beats Claude Opus 4.6). MCP-Atlas 76.4. 1M context window.',
    1000000,
    1.25,
    3.75,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. OpenRouter slug: qwen/qwen3.7-max.',
    'Flagship with 35-hour autonomous coding runs. AA Intelligence Index 56.6 (#5 global). APEX 44.5 (beats Claude Opus 4.6). MCP-Atlas 76.4. 1M context window.',
    'Proprietary — no open weights. High abstention rate (48%) means frequent refusals. Expensive vs Chinese peers ($2.50/$7.50 per million tokens). Not the cheapest option for routine tasks.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'alibaba/qwen3.7-plus',
    'Qwen3.7 Plus',
    'alibaba',
    'Alibaba Qwen3.7 Plus — native multimodal with vision and video input. Very affordable ($0.40/$1.60). Terminal-Bench 70.3. ScreenSpot Pro 79.0. 1M context window. Released June 2, 2026.',
    1000000,
    0.4,
    1.6,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. OpenRouter slug: qwen/qwen3.7-plus. Brand new (released June 2026).',
    'Native multimodal with vision and video input. Very affordable ($0.40/$1.60). Terminal-Bench 70.3. ScreenSpot Pro 79.0. 1M context window. Released June 2, 2026 — latest generation.',
    'Sub-SOTA on pure reasoning benchmarks. Proprietary — no open weights. Brand new (released June 2026) with minimal community testing. Not yet proven for complex agentic workflows.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'alibaba/qwen3.6-plus',
    'Qwen3.6 Plus',
    'alibaba',
    'Alibaba Qwen3.6 Plus — budget-friendly model with good general coding capability. Agent programming enhancement. 1M context window. Solid baseline for cost-sensitive tasks.',
    1000000,
    0.325,
    1.95,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. OpenRouter slug: qwen/qwen3.6-plus.',
    'Budget-friendly Alibaba model with good general coding capability. Agent programming enhancement. Solid baseline for cost-sensitive tasks.',
    'Superseded by Qwen 3.7 series. Not frontier-tier on any benchmark. Limited community benchmarking compared to newer models.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'minimax/minimax-m2.5',
    'MiniMax M2.5',
    'minimax',
    'MiniMax M2.5 — very cheap budget model with surprisingly strong coding performance. SWE-Bench Verified ~80.2%. Good for simple, high-volume tasks where cost matters most.',
    204800,
    0.15,
    1.15,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. Predecessor to M2.7.',
    'Very cheap budget model. SWE-Bench Verified ~80.2% — high score for the price tier. Good for simple, high-volume tasks where cost matters most.',
    'Older generation — less capable than M2.7 and M3 on complex agentic tasks. Not suitable for multi-step reasoning or long-horizon workflows.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'minimax/minimax-m3',
    'MiniMax M3',
    'minimax',
    'MiniMax M3 — first open-weight model combining frontier coding (SWE-Bench Pro 59.0%) with 1M context and multimodal capability. MSA architecture uses 1/20th compute at 1M context. Very affordable ($0.30/$1.20). Released June 1, 2026.',
    1048576,
    0.3,
    1.2,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. Brand new (released June 1, 2026). Open-weight.',
    'First open-weight model combining frontier coding (SWE-Bench Pro 59.0%) + 1M context + multimodal. MSA architecture uses 1/20th compute at 1M context. Very affordable ($0.30/$1.20). Open-weight.',
    'Brand new (released June 1, 2026) — benchmarks not yet verified by third parties. Multimodal ranking lower than text-only peers (#69 on multimodal leaderboard). Limited production track record.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'deepseek/deepseek-v4-pro',
    'DeepSeek V4 Pro',
    'deepseek',
    'DeepSeek V4 Pro — leading agentic open-weight model. LiveCodeBench 93.5. 1M context window. AA Intelligence Index 52. Strong at complex multi-step reasoning and coding tasks.',
    1048576,
    0.435,
    0.87,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. Leading agentic open-weight model.',
    'Leading agentic open-weight model (GDPVal-AA 1554). LiveCodeBench 93.5. 1M context window. AA Intelligence Index 52. Strong at complex multi-step reasoning and coding.',
    'Very high hallucination rate (94% on AA eval). Expensive for an open-weight model ($0.435/$0.87). High token usage — verbose outputs. Not suitable for tasks requiring factual accuracy.',
    NOW()
  ),
  (
    gen_random_uuid(),
    'deepseek/deepseek-v4-flash',
    'DeepSeek V4 Flash',
    'deepseek',
    'DeepSeek V4 Flash — extremely cheap model with reliable tool calling. E2E verified in production. 1M context window. Best value for high-volume, tool-calling tasks.',
    1048576,
    0.0983,
    0.1966,
    false,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'OpenCodeGo-routed. E2E verified for reliable tool calling. Recommended for high-volume tool-calling tasks.',
    'Extremely cheap ($0.098/$0.197 per million tokens). Reliable tool calling — E2E verified in production. 1M context window. Fast inference. Best value option for high-volume, tool-calling tasks.',
    'Less capable on hardest reasoning tasks. Very high hallucination rate (96%). Not suitable for complex multi-step reasoning or factual accuracy tasks.',
    NOW()
  )
ON CONFLICT ("model_id") DO NOTHING;
