import { useEffect, useState } from 'react';
import { fetchBrainPreview } from '@/lib/gateway';
import { MarkdownPreview } from '@/components/MarkdownPreview';
import { CollapsibleSection } from '../components/CollapsibleSection';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import type { Archetype, BrainPreviewResponse } from '@/lib/types';

function AutoGeneratedBlock({ summary, content }: { summary: string; content: string }) {
  const [showDetails, setShowDetails] = useState(false);
  return (
    <div className="space-y-2">
      <p className="text-sm text-muted-foreground">{summary}</p>
      <button
        type="button"
        className="text-xs text-muted-foreground underline decoration-dotted underline-offset-4 hover:text-foreground transition-colors"
        onClick={() => setShowDetails((v) => !v)}
      >
        {showDetails ? 'Hide details ▴' : 'Show full details ▾'}
      </button>
      {showDetails && (
        <div className="mt-2 rounded-md border bg-muted/30 p-4">
          <MarkdownPreview content={content} />
        </div>
      )}
    </div>
  );
}

interface ProfilePreviewSectionProps {
  archetype: Archetype;
  tenantId: string;
}

export function ProfilePreviewSection({ archetype, tenantId }: ProfilePreviewSectionProps) {
  const [data, setData] = useState<BrainPreviewResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchData = () => {
    setLoading(true);
    setError(null);
    fetchBrainPreview(tenantId, archetype.id)
      .then((result) => {
        if (result === null) {
          setError('Preview not available for this employee.');
        } else {
          setData(result);
        }
        setLoading(false);
      })
      .catch((err: unknown) => {
        setError(err instanceof Error ? err.message : 'Could not load preview.');
        setLoading(false);
      });
  };

  useEffect(() => {
    fetchData();
  }, [tenantId, archetype.id]);

  return (
    <CollapsibleSection
      id="section-preview"
      title="What your employee receives"
      subtitle="This is the complete set of instructions and context assembled automatically each time this employee runs"
      defaultOpen={false}
    >
      {loading && (
        <div className="space-y-3">
          {Array.from({ length: 8 }).map((_, i) => (
            <div key={i} className="h-10 animate-pulse rounded-md border bg-muted" />
          ))}
        </div>
      )}

      {error && !loading && (
        <div className="space-y-2">
          <p className="text-sm text-muted-foreground">{error}</p>
          <Button variant="outline" size="sm" onClick={fetchData}>
            Retry
          </Button>
        </div>
      )}

      {!loading && !error && data && (
        <div className="space-y-3">
          <CollapsibleSection
            title="Task prompt"
            defaultOpen={true}
            badge={
              <Badge variant="secondary" className="text-xs font-mono">
                {data.execution_prompt.length.toLocaleString()} chars
              </Badge>
            }
          >
            <MarkdownPreview content={data.execution_prompt} />
          </CollapsibleSection>

          <CollapsibleSection
            title="Compiled AGENTS.md"
            subtitle="Exact file written to the worker container on each run"
            defaultOpen={false}
            badge={
              data.compiled_agents_md ? (
                <Badge variant="secondary" className="text-xs font-mono">
                  {data.compiled_agents_md.length.toLocaleString()} chars
                </Badge>
              ) : null
            }
          >
            {data.compiled_agents_md ? (
              <pre className="max-h-[32rem] overflow-auto rounded-md border bg-muted/50 p-4 font-mono text-xs leading-relaxed whitespace-pre-wrap break-words">
                {data.compiled_agents_md}
              </pre>
            ) : (
              <p className="text-sm text-muted-foreground italic">
                Not available — run the employee once to generate a snapshot.
              </p>
            )}
          </CollapsibleSection>

          <CollapsibleSection
            title="Available tools"
            defaultOpen={false}
            badge={
              <Badge variant="secondary" className="text-xs">
                {data.tools.length} {data.tools.length === 1 ? 'tool' : 'tools'}
              </Badge>
            }
          >
            {data.tools.length > 0 ? (
              <div className="space-y-2">
                {data.tools.map((tool) => (
                  <div key={`${tool.service}/${tool.name}`} className="flex flex-col gap-0.5">
                    <span className="text-sm font-medium font-mono">
                      {tool.service}/{tool.name}
                    </span>
                    <span className="text-xs text-muted-foreground">{tool.description}</span>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-sm text-muted-foreground italic">No tools configured.</p>
            )}
          </CollapsibleSection>

          <CollapsibleSection
            title="Learned rules"
            defaultOpen={false}
            badge={
              <Badge variant="secondary" className="text-xs">
                {data.employee_rules.length} {data.employee_rules.length === 1 ? 'rule' : 'rules'}
              </Badge>
            }
          >
            {data.employee_rules.length > 0 ? (
              <MarkdownPreview content={data.employee_rules.join('\n\n')} />
            ) : (
              <p className="text-sm text-muted-foreground italic">No rules learned yet.</p>
            )}
          </CollapsibleSection>

          <CollapsibleSection
            title="Knowledge base"
            defaultOpen={false}
            badge={
              <Badge variant="secondary" className="text-xs">
                {data.employee_knowledge.length}{' '}
                {data.employee_knowledge.length === 1 ? 'entry' : 'entries'}
              </Badge>
            }
          >
            {data.employee_knowledge.length > 0 ? (
              <MarkdownPreview content={data.employee_knowledge.join('\n\n')} />
            ) : (
              <p className="text-sm text-muted-foreground italic">No knowledge base entries.</p>
            )}
          </CollapsibleSection>
        </div>
      )}
    </CollapsibleSection>
  );
}
