// @generated by scripts/generate-worker-constants.ts — do not edit
// Source: src/lib/output-contract-constants.ts

export const SUMMARY_PATH = '/tmp/summary.txt';
export const APPROVAL_MESSAGE_PATH = '/tmp/approval-message.json';
export const DRAFT_PATH = '/tmp/draft.txt';
export const DELIVERY_PHASE_VALUE = 'delivery';
export const EXECUTION_PHASE_VALUE = 'execution';
export const OUTPUT_CONTRACT_VERSION = 1;
export type OutputClassification = 'APPROVED' | 'NEEDS_APPROVAL' | 'NO_ACTION_NEEDED';
