#!/usr/bin/env tsx
/**
 * generate-worker-constants — emits the World-B copy of the output-contract constants.
 *
 * Single source of truth: src/lib/output-contract-constants.ts (World A — compiled
 * gateway/workers). World B (src/worker-tools/, tsx-isolated) MUST NOT import from
 * src/lib/, so it receives a GENERATED copy instead. This script reads the authored
 * values and emits src/worker-tools/lib/output-contract-paths.generated.ts.
 *
 * The OutputClassification type is emitted as a literal union (not a re-export): World B
 * cannot import the type from World A, so the union literal is duplicated here. The CI
 * diff gate (see .github/workflows/deploy.yml) proves the two copies stay in sync.
 *
 * Output is deterministic and uses LF line endings.
 *
 * Usage:
 *   pnpm generate-worker-constants
 *   tsx scripts/generate-worker-constants.ts
 *
 * No API key required — pure local codegen.
 */

import { createRequire } from 'module';
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join, resolve } from 'path';
import { fileURLToPath } from 'url';

const _require = createRequire(import.meta.url);
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolve(__dirname, '..');

try {
  const dotenv = _require('dotenv');
  dotenv.config({ path: join(repoRoot, '.env') });
} catch {
  // dotenv unavailable — process.env must already be populated (none required here)
}

import {
  APPROVAL_MESSAGE_PATH,
  DELIVERY_PHASE_VALUE,
  DRAFT_PATH,
  EXECUTION_PHASE_VALUE,
  OUTPUT_CONTRACT_VERSION,
  SUMMARY_PATH,
} from '../src/lib/output-contract-constants.js';

const OUTPUT_PATH = join(
  repoRoot,
  'src',
  'worker-tools',
  'lib',
  'output-contract-paths.generated.ts',
);

// OutputClassification is a TYPE — it cannot be read at runtime. World B cannot import it
// from World A, so the literal union is emitted here verbatim. Source of truth for the
// values: StandardOutput['classification'] in src/workers/lib/output-schema.mts.
const OUTPUT_CLASSIFICATION_UNION = "'APPROVED' | 'NEEDS_APPROVAL' | 'NO_ACTION_NEEDED'";

function normaliseLf(content: string): string {
  return content.replace(/\r\n/g, '\n');
}

/**
 * Writes a file only when content has changed — keeps mtime stable on idempotent re-runs,
 * which keeps `git diff` clean when the script is run twice with no source changes.
 */
function writeIfChanged(filePath: string, content: string): 'written' | 'unchanged' {
  const normalised = normaliseLf(content);
  if (existsSync(filePath)) {
    const existing = readFileSync(filePath, 'utf8');
    if (existing === normalised) {
      return 'unchanged';
    }
  }
  writeFileSync(filePath, normalised, { encoding: 'utf8', flag: 'w' });
  return 'written';
}

function buildGeneratedFile(): string {
  const lines = [
    '// @generated by scripts/generate-worker-constants.ts — do not edit',
    '// Source: src/lib/output-contract-constants.ts',
    '',
    `export const SUMMARY_PATH = '${SUMMARY_PATH}';`,
    `export const APPROVAL_MESSAGE_PATH = '${APPROVAL_MESSAGE_PATH}';`,
    `export const DRAFT_PATH = '${DRAFT_PATH}';`,
    `export const DELIVERY_PHASE_VALUE = '${DELIVERY_PHASE_VALUE}';`,
    `export const EXECUTION_PHASE_VALUE = '${EXECUTION_PHASE_VALUE}';`,
    `export const OUTPUT_CONTRACT_VERSION = ${OUTPUT_CONTRACT_VERSION};`,
    `export type OutputClassification = ${OUTPUT_CLASSIFICATION_UNION};`,
  ];
  return lines.join('\n') + '\n';
}

function main(): void {
  const content = buildGeneratedFile();
  const result = writeIfChanged(OUTPUT_PATH, content);
  console.log(
    `[generate-worker-constants] ${result === 'written' ? 'Wrote' : 'Up to date'}: ${OUTPUT_PATH}`,
  );
}

main();
