#!/usr/bin/env tsx
/**
 * register-project — Interactive wizard to register a new project via the admin API
 *
 * Guides the user through supplying all required and optional fields for a project,
 * shows a confirmation summary, then calls POST /admin/projects. On success, prints
 * the project ID and next-step instructions.
 *
 * Usage:
 *   npx tsx scripts/register-project.ts
 *   pnpm register-project
 *
 * Options:
 *   --help   Show this help
 *
 * Environment variables read from .env:
 *   ADMIN_API_KEY   Admin API key (auto-generated by pnpm setup)
 *   GATEWAY_BASE    Gateway base URL (default: http://localhost:3000)
 */

import { readFileSync, existsSync } from 'node:fs';
import { $, question } from 'zx';

// Suppress zx command echoing — we control all output manually
$.verbose = false;

// ─── ANSI color helpers (same palette as setup.ts) ───────────────────────────

const C = {
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  blue: '\x1b[34m',
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
};

function ok(msg: string, detail?: string) {
  console.log(`${C.green}✓${C.reset} ${msg}${detail ? ` ${C.cyan}(${detail})${C.reset}` : ''}`);
}
function info(msg: string, detail?: string) {
  console.log(`${C.blue}→${C.reset} ${msg}${detail ? ` ${C.dim}${detail}${C.reset}` : ''}`);
}
function warn(msg: string) {
  console.log(`${C.yellow}⚠${C.reset} ${msg}`);
}
function fail(msg: string) {
  console.error(`${C.red}✗${C.reset} ${msg}`);
}
function section(name: string) {
  console.log(`\n${C.bold}${C.cyan}── ${name} ──${C.reset}`);
}
function status(label: string, value: string) {
  console.log(`  ${C.dim}${label}:${C.reset} ${C.bold}${value}${C.reset}`);
}

// ─── Argument parsing ─────────────────────────────────────────────────────────

const argv = process.argv.slice(2);
const helpFlag = argv.includes('--help') || argv.includes('-h');

if (helpFlag) {
  console.log(`
${C.bold}register-project${C.reset} — Interactive wizard to register a new project

${C.bold}Usage:${C.reset}
  npx tsx scripts/register-project.ts
  pnpm register-project

${C.bold}Description:${C.reset}
  Guides you through registering a new project via the admin API.
  Prompts for all required and optional fields, then calls POST /admin/projects.

${C.bold}Environment variables (read from .env):${C.reset}
  ${C.cyan}ADMIN_API_KEY${C.reset}   Admin API key (auto-generated by pnpm setup)
  ${C.cyan}GATEWAY_BASE${C.reset}    Gateway base URL (default: http://localhost:3000)

${C.bold}What it does:${C.reset}
  1. Prompts for project name, repo URL, Jira key, and optional tooling config
  2. Shows a confirmation summary before sending
  3. POSTs to /admin/projects with the collected data
  4. Shows the created project ID and next-step instructions on success
`);
  process.exit(0);
}

// ─── .env loader ──────────────────────────────────────────────────────────────

/**
 * Parse .env file into a Record<string, string>.
 * Strips surrounding double-quotes from values (e.g. VAR="value" → "value").
 * Does NOT set process.env — returns an object for explicit access.
 */
function loadEnv(): Record<string, string> {
  const env: Record<string, string> = {};
  if (!existsSync('.env')) return env;
  const content = readFileSync('.env', 'utf8');
  for (const line of content.split('\n')) {
    // Match KEY=value or KEY="value" — skip comments and blank lines
    const match = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (match) {
      env[match[1]] = match[2].replace(/^"|"$/g, '').replace(/^'|'$/g, '');
    }
  }
  return env;
}

const dotenv = loadEnv();

// Prefer process.env overrides (e.g. ADMIN_API_KEY=xxx npx tsx ...)
// Fall back to .env file values
function getEnv(key: string): string {
  return process.env[key] ?? dotenv[key] ?? '';
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  section('Register New Project');
  info('This wizard will register a new project via the admin API.');
  info('Press Ctrl+C at any time to abort.\n');

  const adminKey = getEnv('ADMIN_API_KEY');
  const gatewayBase = getEnv('GATEWAY_BASE') || 'http://localhost:3000';

  if (!adminKey) {
    fail('ADMIN_API_KEY not set — add it to .env or generate with: openssl rand -hex 32');
    fail('Run pnpm setup to auto-generate it.');
    process.exit(1);
  }

  status('gateway', gatewayBase);

  // ── 1–3. Required fields ──────────────────────────────────────────────────

  section('Required Fields');

  // 1. name
  let name = '';
  while (!name) {
    name = (await question('Project display name: ')).trim();
    if (!name) warn('Project name cannot be empty.');
  }

  // 2. repo_url
  let repoUrl = '';
  while (true) {
    repoUrl = (await question('GitHub repo URL (https://github.com/owner/repo): ')).trim();
    if (!repoUrl) {
      warn('Repo URL cannot be empty.');
      continue;
    }
    if (!repoUrl.startsWith('https://github.com/')) {
      warn('Repo URL must start with https://github.com/');
      continue;
    }
    const afterDomain = repoUrl.replace('https://github.com/', '');
    if (afterDomain.split('/').filter(Boolean).length < 2) {
      warn('Repo URL must include org and repo: https://github.com/owner/repo');
      continue;
    }
    break;
  }

  // 3. jira_project_key
  let jiraProjectKey = '';
  while (!jiraProjectKey) {
    jiraProjectKey = (await question('Jira project key (e.g. TEST, MYPROJ): '))
      .trim()
      .toUpperCase();
    if (!jiraProjectKey) warn('Jira project key cannot be empty.');
  }

  // ── 4–5. Optional fields ──────────────────────────────────────────────────

  section('Optional Fields');

  // 4. default_branch
  const defaultBranchInput = (await question('Default branch [main]: ')).trim();
  const defaultBranch = defaultBranchInput || 'main';

  // 5. tooling_config.install
  const installInput = (
    await question('Install command [pnpm install --frozen-lockfile]: ')
  ).trim();
  const installCommand = installInput || 'pnpm install --frozen-lockfile';

  // ── 6–10. Advanced tooling (optional) ────────────────────────────────────

  const advancedAnswer = (await question('Configure advanced tooling? [y/N]: '))
    .trim()
    .toLowerCase();
  const configureAdvanced = advancedAnswer === 'y';

  let typescriptCmd = '';
  let lintCmd = '';
  let unitCmd = '';
  let integrationCmd = '';
  let e2eCmd = '';

  if (configureAdvanced) {
    section('Advanced Tooling');
    typescriptCmd = (await question('TypeScript check command [leave blank to skip]: ')).trim();
    lintCmd = (await question('Lint command [leave blank to skip]: ')).trim();
    unitCmd = (await question('Unit test command [leave blank to skip]: ')).trim();
    integrationCmd = (await question('Integration test command [leave blank to skip]: ')).trim();
    e2eCmd = (await question('E2E test command [leave blank to skip]: ')).trim();
  }

  // ── Confirmation summary ──────────────────────────────────────────────────

  section('Confirm Registration');
  console.log(`  ${C.dim}name:${C.reset}              ${C.bold}${name}${C.reset}`);
  console.log(`  ${C.dim}repo_url:${C.reset}          ${C.bold}${repoUrl}${C.reset}`);
  console.log(`  ${C.dim}jira_project_key:${C.reset}  ${C.bold}${jiraProjectKey}${C.reset}`);
  console.log(`  ${C.dim}default_branch:${C.reset}    ${C.bold}${defaultBranch}${C.reset}`);
  console.log(`  ${C.dim}install command:${C.reset}   ${C.bold}${installCommand}${C.reset}`);

  if (configureAdvanced) {
    if (typescriptCmd)
      console.log(`  ${C.dim}typescript:${C.reset}        ${C.bold}${typescriptCmd}${C.reset}`);
    if (lintCmd)
      console.log(`  ${C.dim}lint:${C.reset}              ${C.bold}${lintCmd}${C.reset}`);
    if (unitCmd)
      console.log(`  ${C.dim}unit:${C.reset}              ${C.bold}${unitCmd}${C.reset}`);
    if (integrationCmd)
      console.log(`  ${C.dim}integration:${C.reset}       ${C.bold}${integrationCmd}${C.reset}`);
    if (e2eCmd) console.log(`  ${C.dim}e2e:${C.reset}               ${C.bold}${e2eCmd}${C.reset}`);
  }

  console.log();
  const proceedAnswer = (await question('Proceed? [Y/n]: ')).trim().toLowerCase();
  if (proceedAnswer === 'n') {
    warn('Registration cancelled.');
    process.exit(0);
  }

  // ── Build request body ────────────────────────────────────────────────────

  // Only include non-empty tooling sub-fields
  const toolingConfig: Record<string, string> = { install: installCommand };
  if (typescriptCmd) toolingConfig['typescript'] = typescriptCmd;
  if (lintCmd) toolingConfig['lint'] = lintCmd;
  if (unitCmd) toolingConfig['unit'] = unitCmd;
  if (integrationCmd) toolingConfig['integration'] = integrationCmd;
  if (e2eCmd) toolingConfig['e2e'] = e2eCmd;

  // Only include tooling_config if at least one field is non-empty
  const hasTooling = Object.values(toolingConfig).some((v) => v.length > 0);

  const body: Record<string, unknown> = {
    name,
    repo_url: repoUrl,
    jira_project_key: jiraProjectKey,
    default_branch: defaultBranch,
  };

  if (hasTooling) {
    body['tooling_config'] = toolingConfig;
  }

  // ── API call ──────────────────────────────────────────────────────────────

  section('Registering Project');
  info(`POST ${gatewayBase}/admin/projects`);

  let response: Response;
  try {
    response = await fetch(`${gatewayBase}/admin/projects`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Admin-Key': adminKey,
      },
      body: JSON.stringify(body),
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    fail(`Cannot reach gateway at ${gatewayBase}`);
    fail(`  ${msg}`);
    fail('Is it running? Start with: pnpm dev:start');
    process.exit(1);
  }

  const responseText = await response.text();
  let responseJson: Record<string, unknown> = {};
  try {
    responseJson = JSON.parse(responseText);
  } catch {
    // Non-JSON response — handled below
  }

  // ── Response handling ─────────────────────────────────────────────────────

  if (response.status === 401) {
    fail('Invalid ADMIN_API_KEY — check your .env file.');
    process.exit(1);
  }

  if (response.status === 409) {
    fail(`A project with Jira key ${jiraProjectKey} is already registered.`);
    process.exit(1);
  }

  if (response.status === 400) {
    fail('Validation error — the server rejected the request:');
    const issues = responseJson['issues'];
    if (Array.isArray(issues)) {
      for (const issue of issues) {
        fail(`  ${String(issue)}`);
      }
    } else {
      fail(`  ${responseText}`);
    }
    process.exit(1);
  }

  if (response.status !== 201) {
    fail(`Unexpected response HTTP ${response.status}`);
    fail(`  ${responseText}`);
    process.exit(1);
  }

  // ── 201 success ───────────────────────────────────────────────────────────

  const projectId = String(responseJson['id'] ?? '');

  section('Success');
  ok('Project registered successfully!');
  status('id', projectId);
  status('name', String(responseJson['name'] ?? name));
  status('jira_project_key', String(responseJson['jira_project_key'] ?? jiraProjectKey));
  status('repo_url', String(responseJson['repo_url'] ?? repoUrl));
  status('default_branch', String(responseJson['default_branch'] ?? defaultBranch));

  // ── Next steps ────────────────────────────────────────────────────────────

  section('Next Steps');
  console.log(
    `${C.blue}→${C.reset} Your project is registered. To have the AI develop a ticket:\n`,
  );
  console.log(
    `  ${C.bold}1.${C.reset} Send a Jira webhook with project key "${C.bold}${jiraProjectKey}${C.reset}":`,
  );
  console.log(`       pnpm trigger-task --key ${jiraProjectKey}-1\n`);
  console.log(`     The webhook payload at test-payloads/jira-realistic-task.json will be used.`);
  console.log(
    `     Edit it to set issue.fields.project.key = "${jiraProjectKey}" and write your ticket`,
  );
  console.log(`     summary + description, then run the command above.\n`);
  console.log(
    `  ${C.bold}2.${C.reset} Monitor progress — the script polls until Done and prints the PR URL.\n`,
  );
  console.log(`  ${C.bold}3.${C.reset} Verify with:`);
  console.log(`       pnpm verify:e2e --task-id <task-id-from-output>\n`);
  console.log(`${C.blue}→${C.reset} Project ID: ${C.bold}${projectId}${C.reset}`);
  console.log(`${C.blue}→${C.reset} Manage via:`);
  console.log(`     GET    ${gatewayBase}/admin/projects/${projectId}`);
  console.log(`     PATCH  ${gatewayBase}/admin/projects/${projectId}`);
  console.log(`     DELETE ${gatewayBase}/admin/projects/${projectId}`);
  console.log(`  ${C.dim}(all require X-Admin-Key header)${C.reset}`);
  console.log();
}

// ─── Entry point ──────────────────────────────────────────────────────────────

main().catch((err) => {
  fail(`Unhandled error: ${err instanceof Error ? err.message : String(err)}`);
  if (err instanceof Error && err.stack) {
    console.error(C.dim + err.stack + C.reset);
  }
  process.exit(1);
});
